// <auto-generated />
using System;
using AlumnosMicorservicio.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlumnosMicorservicio.Migrations
{
    [DbContext(typeof(ContextoAlumnos))]
    [Migration("20230212203241_AlumnosDB")]
    partial class AlumnosDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AlumnosMicorservicio.Modelo.AlumnoInscrito", b =>
                {
                    b.Property<int>("AlumnoInscritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AlumnoInscritoGuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreAlumno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlumnoInscritoId");

                    b.ToTable("AlumnoInscrito");
                });

            modelBuilder.Entity("AlumnosMicorservicio.Modelo.CarreraAlumno", b =>
                {
                    b.Property<int>("CarreraAlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AlumnoInscritoId")
                        .HasColumnType("int");

                    b.Property<string>("CarreraAlumnoGuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControlCarrera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCarrera")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarreraAlumnoId");

                    b.HasIndex("AlumnoInscritoId");

                    b.ToTable("CarreraAlumno");
                });

            modelBuilder.Entity("AlumnosMicorservicio.Modelo.CarreraAlumno", b =>
                {
                    b.HasOne("AlumnosMicorservicio.Modelo.AlumnoInscrito", "AlumnoInscrito")
                        .WithMany("CarrerasAlumnos")
                        .HasForeignKey("AlumnoInscritoId");

                    b.Navigation("AlumnoInscrito");
                });

            modelBuilder.Entity("AlumnosMicorservicio.Modelo.AlumnoInscrito", b =>
                {
                    b.Navigation("CarrerasAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
